/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dlmspiv;

import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aziza
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    JLabel l1;
    
    public NewJFrame4() {
        initComponents();
        Font f1 = new Font("Dialog", Font.PLAIN, 34);
        l1 = new JLabel("ВАШ УРОВЕНЬ ЗРЕНИЯ: ");
        l1.setFont(f1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Logo2.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("2.1 КАК ВЫ ВЫБРАЛИ ПРОФЕССИЮ?");

        jComboBox5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ДА", "B. НЕ ОЧЕНЬ", "С. НЕТ" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("2.2 МОЖНО ЛИ ВАС НАЗВАТЬ ОБЩИТЕЛЬНЫМ ЧЕЛОВЕКОМ?");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("2. ОСОБЕННОСТИ ПОЗНАВАТЕЛЬНОЙ ДЕЯТЕЛЬНОСТИ:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("1. ВОЗРАСТ");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. 17-20", "B. ВЫШЕ 21", "С. ВЫШЕ 35" }));

        jComboBox7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ВЫСОКАЯ", "B. СРЕДНЯЯ", "С. НИЗКАЯ" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setText("2.5 ПОЗНАВАТЕЛЬНАЯ АКТИВНОСТЬ (СТРЕМЛЕНИПЕ К НОВЫМ ЗНАНИЯМ):");

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. ИСХОДЯ ИЗ ПРАКТИЧЕСКИХ СООБРАЖЕНИЙ", "B. БЛАГОДАРЯ СЛУЧАЙНОМУ СТЕЧЕНИЮ ОБСТОЯТЕЛЬСТВ", "С. ОСТАНОВИЛ СВОЙ ВЫБОР НА ПЕРВОМ, ЧТО БОЛЕЕ-МЕНЕЕ МНЕ ПОДОШЛО" }));

        jComboBox4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ДА", "B. НЕ ОЧЕНЬ", "С. НЕТ" }));

        jComboBox6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ON-LINE", "B. OFF-LINE", "С. ТРАДИЦИОННОЕ" }));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("2.4 КАКОЙ СПОСОБ УЧЕБЫ ДЛЯ ВАС ПРЕДПОЧТИТЕЛЬНЕЕ?");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setText("2.3 ВЫ ЛЕГКО УСВАИВАЕТЕ НОВЫЙ МАТЕРИАЛ?");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("6. ЛОГИЧЕСКОЙ МЫШЛЕНИЕ:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setText("3.1 КОГДА У ВАС ЧТО-ТО НЕ ПОЛУЧАЕТСЯ, ВЫ:");

        jComboBox8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ПРОДОЛЖАЕТЕ НАЧАТОЕ ДЕЛО", "B. КАКОЕ-ТО ВРЕМЯ ВСЕ РАВНО ПРОДОЛЖАЕТЕ ДЕЙСТВОВАТЬ\"", "С. ОТКАЗЫВАЕТЕСЬ ОТ ЗАТЕИ КАК ОТ НЕРЕАЛЬНОЙ" }));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setText("3.2 В ЗАТРУДНИТЕЛЬНЫХ СИТУАЦИЯХ, КАСАЮЩИЕСЯ УЧЕБЫ:");

        jComboBox9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. НЕ ЛЮБИТЕ ОБРАЩАТЬСЯ, РЕШАЕТЕ САМОСТОЯТЕЛЬНО", "B. СПЕШИТЕ ОБРАТИТЬСЯ ЗА ПОМОЩЬЮ К ДРУГИМ", "С. ОСТАВЛЯЕТЕ ВСЕ КАК ЕСТЬ" }));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("3.ПСИХОЛОГИЧЕСКИЙ И ВОЛЕВОЙ ПОТЕНЦИАЛ ЛИЧНОСТИ:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel14.setText("4.1 ПОЗВОЛЯЕТ ЛИ ВАМ ЗДОРОВЬЕ НАПРЯЖЕННО ЗАНИМАТЬСЯ УЧЕБОЙ?");

        jComboBox10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ДА", "B. УМЕРЕННО", "С. НЕТ" }));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel15.setText("4.2 ВАША ПАМЯТЬ?");

        jComboBox11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ХОРОШАЯ", "B. СРЕДНЯЯ", "С. ПЛОХАЯ" }));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setText("4.ФИЗИОЛОГИЧЕСКИЙ ПОТЕНЦИАЛ ЛИЧНОСТИ:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel17.setText("5.1 УБЕЖДЕНЫ ЛИ ВЫ В НЕОБХОДИМОСТИ ПОЛУЧЕНИЯ КАКОЙ- ЛИБО ПОЛЕЗНОЙ КВАЛИФИКАЦИИ?");

        jComboBox12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ДА", "B. В НЕКОТОРОЙ СТЕПЕНИ", "С. НЕТ" }));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel18.setText("5.2 КОГДА ВЫ БЕРЕТЕСЬ ЗА САМОСТОЯТЕЛЬНОЕ ОБУЧЕНИЕ, ЕСТЬ ЛИ УВЕРЕННОСТЬ, В ТОМ, ЧТО ВЫ ОСУЩЕСТВИТЕ СВОЕ НАЧИНАНИЕ?");

        jComboBox13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A. ДА", "B. ЧАСТО БЫВАЮТ СОМНЕНИЯ", "С. НЕТ" }));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel19.setText("5.3 БЫВАЕТ ЛИ У ВАС ЖЕЛАНИЕ ЗАНЯТЬСЯ ОБУЧЕНИЕМ СОВЕРШЕННО НОВОЙ, НЕЗНАКОМОЙ ДИСЦИПЛИНЫ?");

        jComboBox14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. ДА, НЕИЗВЕСТНОЕ МЕНЯ ПРИВЛЕКАЕТ", "B. ВСЕ ЗАВИСИТ ОТ СОДЕРЖАНИЯ ЭТОЙ ОБЛАСТИ ОБУЧЕНИЯ", "С. НЕИЗВЕСТНОЕ МЕНЯ НЕ ИНТЕРЕСУЕТ" }));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel20.setText("5.4 ЗАНИМАЯСЬ ОБУЧЕНИЕМ НОВОЙ ДИСЦИПЛИНЫ, СТРЕМИТЕСЬ ЛИ ВЫ ДОБИТЬСЯ В НЕМ СОВЕРШЕНСТВА?");

        jComboBox15.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. ДА", "B. УДОВЛЕТВОРИТЕСЬ ТЕМ, ЧЕГО СМОГЛИ ДОБИТЬСЯ", "С. НЕТ" }));
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel21.setText("5.МОТИВАЦИОННЫЙ ПОТЕНЦИАЛ ЛИЧНОСТИ:");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel22.setText("6.1 ВСТАВЬТЕ НЕДОСТАЮЩЕЕ ЧИСЛО");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/6.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel24.setText("7.ТЕХНИКА ЧТЕНИЯ (180, 156, 189, 190, 200,230,250)");

        jComboBox17.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "156", "180", "189", "190", "200", "230", "250" }));
        jComboBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox17ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel25.setText("8.ВОСПРИЯТИЕ ИНФОРМАЦИИ:");

        jComboBox18.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. СЛУХОВОЕ ВОСПРИЯТИЕ", "B. ЗРИТЕЛЬНОЕ ВОСПРИЯТИЕ", "С. ОСЯЗАНИЕ" }));
        jComboBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox18ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel26.setText("9.СОСТОЯНИЕ ЗДОРОВЬЕ ПО ДЕФЕКТУ ЗРЕНИЯ:");

        jComboBox19.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A. ПРИ ЭММЕТРОПИИ (НОРМАЛЬНОМ ЗРЕНИИ) ГЛАЗ ВИДИТ БУКВЫ С ОБЕИХ СТОРОН ОДИНАКОВЫМИ ПО ТЕМНОТЕ И ЧЕТКОСТИ.", "B. ЕСЛИ СИМВОЛЫ КАЖУТСЯ БОЛЕЕ ЧЕТКИМИ НА КРАСНОМ ФОНЕ, ТО СУЩЕСТВУЕТ БОЛЬШАЯ ВЕРОЯТНОСТЬ НАЛИЧИЯ БЛИЗОРУКОСТИ.", "С. ЕСЛИ НА ЗЕЛЕНОМ, ТО МОЖНО ПРЕДПОЛОЖИТЬ НАЛИЧИЕ ДАЛЬНОЗОРКОСТИ." }));
        jComboBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox19ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/9.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel28.setText("10.ОПРЕДЕЛЕНИЕ ОСТРОТЫ ЗРЕНИЯ");

        jComboBox20.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "СЛАБОВИДЯЩИЕ (С ГИПЕРМЕТРОПИЕЙ)", "СЛАБОВИДЯЩИЕ (С МИОПИЕЙ)", "СЛЕПЫЕ", "ЧАСТИЧНО ЗРЯЧИЕ (С ГИПЕРМЕТРОПИЕЙ)", "ЧАСТИЧНО ЗРЯЧИЕ (С МИОПИЕЙ)", "ЭММЕТРОПИЯ" }));
        jComboBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox20ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("ДАЛЕЕ");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jComboBox10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel27))
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(25, 25, 25)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel26)
                .addGap(26, 26, 26)
                .addComponent(jLabel27)
                .addGap(33, 33, 33)
                .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ТЕСТ НА ПОСТРОЕНИЯ ЗРИТЕЛЬНОЙ МОДЕЛИ ОБУЧАЮЩИХСЯ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(713, 713, 713))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jComboBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox17ActionPerformed

    private void jComboBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox18ActionPerformed

    private void jComboBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox19ActionPerformed

    private void jComboBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox20ActionPerformed

    PreparedStatement preparedStatement = null;
    private static final String UPDATE_NEW = "UPDATE users SET levelDis = ? WHERE login = ?";
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        switch (jComboBox1.getSelectedIndex()){
            case 0: LableQ.S1 = 0;
            break;
            case 1: LableQ.S1 = 3;
            break;
            case 2: LableQ.S1 = 2;
            break;
            case 3: LableQ.S1 = 1;
           break;
        }
         switch (jComboBox3.getSelectedIndex()){
            case 0: LableQ.S2_1 = 0;
            break;
            case 1: LableQ.S2_1 = 3;
            break;
            case 2: LableQ.S2_1 = 2;
            break;
            case 3: LableQ.S2_1 = 1;
           break;
        }
         switch (jComboBox4.getSelectedIndex()){
            case 0: LableQ.S2_2 = 0;
            break;
            case 1: LableQ.S2_2 = 3;
            break;
            case 2: LableQ.S2_2 = 2;
            break;
            case 3: LableQ.S2_2 = 1;
           break;
        }
         switch (jComboBox5.getSelectedIndex()){
            case 0: LableQ.S2_3 = 0;
            break;
            case 1: LableQ.S2_3 = 3;
            break;
            case 2: LableQ.S2_3 = 2;
            break;
            case 3: LableQ.S2_3 = 1;
           break;
        }
         switch (jComboBox6.getSelectedIndex()){
            case 0: LableQ.S2_4 = 0;
            break;
            case 1: LableQ.S2_4 = 3;
            break;
            case 2: LableQ.S2_4 = 2;
            break;
            case 3: LableQ.S2_4 = 1;
           break;
        }
          switch (jComboBox7.getSelectedIndex()){
            case 0: LableQ.S2_5 = 0;
            break;
            case 1: LableQ.S2_5 = 3;
            break;
            case 2: LableQ.S2_5 = 2;
            break;
            case 3: LableQ.S2_5 = 1;
           break;
        }
          switch (jComboBox8.getSelectedIndex()){
            case 0: LableQ.S3_1 = 0;
            break;
            case 1: LableQ.S3_1 = 3;
            break;
            case 2: LableQ.S3_1 = 2;
            break;
            case 3: LableQ.S3_1 = 1;
           break;
        }
           switch (jComboBox9.getSelectedIndex()){
            case 0: LableQ.S3_2 = 0;
            break;
            case 1: LableQ.S3_2 = 3;
            break;
            case 2: LableQ.S3_2 = 2;
            break;
            case 3: LableQ.S3_2 = 1;
           break;
        }
            switch (jComboBox10.getSelectedIndex()){
            case 0: LableQ.S4_1 = 0;
            break;
            case 1: LableQ.S4_1 = 3;
            break;
            case 2: LableQ.S4_1 = 2;
            break;
            case 3: LableQ.S4_1 = 1;
           break;
        }
            switch (jComboBox11.getSelectedIndex()){
            case 0: LableQ.S4_2 = 0;
            break;
            case 1: LableQ.S4_2 = 3;
            break;
            case 2: LableQ.S4_2 = 2;
            break;
            case 3: LableQ.S4_2 = 1;
           break;
        }
            switch (jComboBox12.getSelectedIndex()){
            case 0: LableQ.S5_1 = 0;
            break;
            case 1: LableQ.S5_1 = 3;
            break;
            case 2: LableQ.S5_1 = 2;
            break;
            case 3: LableQ.S5_1 = 1;
           break;
        }
            switch (jComboBox13.getSelectedIndex()){
            case 0: LableQ.S5_2 = 0;
            break;
            case 1: LableQ.S5_2 = 3;
            break;
            case 2: LableQ.S5_2 = 2;
            break;
            case 3: LableQ.S5_2 = 1;
           break;
        }
            switch (jComboBox14.getSelectedIndex()){
            case 0: LableQ.S5_3 = 0;
            break;
            case 1: LableQ.S5_3 = 3;
            break;
            case 2: LableQ.S5_3 = 2;
            break;
            case 3: LableQ.S5_3 = 1;
           break;
        }
            switch (jComboBox15.getSelectedIndex()){
            case 0: LableQ.S5_4 = 0;
            break;
            case 1: LableQ.S5_4 = 3;
            break;
            case 2: LableQ.S5_4 = 2;
            break;
            case 3: LableQ.S5_4 = 1;
           break;
        }
         String textNumb = jTextField1.getText();
         
            if(!textNumb.equals("")){
            if ( Integer.parseInt(textNumb) == 24){
            LableQ.S6 = 2;
        } else{LableQ.S6 = 0;}
            
            }
            
         
            
            switch (jComboBox17.getSelectedIndex()){
            case 0: LableQ.S7 = 0;
            break;
            case 1: LableQ.S7 = 1;
            break;
            case 2: LableQ.S7 = 1;
            break;
            case 3: LableQ.S7 = 1;
            break;
            case 4: LableQ.S7 = 2;
            break;
            case 5: LableQ.S7 = 2;
            break;
            case 6: LableQ.S7 = 3;
            break;
            case 7: LableQ.S7 = 3;
        }
            switch (jComboBox18.getSelectedIndex()){
            case 0: LableQ.S8 = 0;
            break;
            case 1: LableQ.S8 = 3;
            break;
            case 2: LableQ.S8 = 2;
            break;
            case 3: LableQ.S8 = 1;
            break;
        }
            switch (jComboBox19.getSelectedIndex()){
            case 0: LableQ.S9 = 0;
            break;
            case 1: LableQ.S9 = 3;
            break;
            case 2: LableQ.S9 = 2;
            break;
            case 3: LableQ.S9 = 1;
            break;
        }
            switch (jComboBox20.getSelectedIndex()){
            case 0: LableQ.S9 = 0;
            break;
            case 1: LableQ.S9 = 3;
            break;
            case 2: LableQ.S9 = 3;
            break;
            case 3: LableQ.S9 = 2;
            break;
            case 4: LableQ.S9 = 2;
            break;
            case 5: LableQ.S9 = 1;
            break;
            case 6: LableQ.S9 = 1;
            break;

        }
            
         LableQ.RESULT = LableQ.S1 + LableQ.S2_1+LableQ.S2_2+LableQ.S2_3+LableQ.S2_4+LableQ.S2_5+LableQ.S3_1+LableQ.S3_2+LableQ.S4_1
						+LableQ.S4_2+LableQ.S5_1+LableQ.S5_2+LableQ.S5_3+LableQ.S5_4+LableQ.S6+LableQ.S7+LableQ.S8+LableQ.S9+LableQ.S10;
				
				//result.setText("Всего набрано баллов:"+LableQ.RESULT);
				System.out.println(LableQ.RESULT);
				System.out.println(LableQ.S6);
                                
				                 try{  
       
                                    Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
                                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dlmspiv_bd?" + "user=root&password=root");     
       
                                    Statement st = (Statement) conn.createStatement();
                                    preparedStatement = conn.prepareStatement(UPDATE_NEW);
                                    
                                   
                                  
                                if(LableQ.RESULT < 17){
                                     
                                     preparedStatement.setInt(1, 1);
                                     preparedStatement.setString(2, LableQ.currentStudent);
                                     LableQ.levelDisStudent = "МИОПИЯ";
                                    
                                     
                                }else if(LableQ.RESULT > 18 && LableQ.RESULT < 35){
                                     
                                     preparedStatement.setInt(1, 2);
                                     preparedStatement.setString(2, LableQ.currentStudent);
                                     LableQ.levelDisStudent = "ГИПЕРМЕТРОПИЯ";
                                     
                                }else if(LableQ.RESULT > 36){
                                     
                                     preparedStatement.setInt(1, 3);
                                     preparedStatement.setString(2, LableQ.currentStudent);
                                    LableQ.levelDisStudent = "АСТИГМАТИЗМ";
                                     
                                } 

                                     preparedStatement.execute();
       
       
                                    }
                                    catch(Exception e){
                                    e.printStackTrace();
                                    
                                    
       
   } 
                    JOptionPane.showMessageDialog( null, "ВАШ УРОВЕНЬ ЗРЕНИЯ: "  + LableQ.levelDisStudent, "Уведомление", JOptionPane.DEFAULT_OPTION);                             
                    new NewJFrame3().setVisible(true);
                    setVisible(false);   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || c == KeyEvent.VK_DELETE) || (jTextField1.getText().length() >= 2)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
