/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dlmspiv;



import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.scene.control.PasswordField;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import java.awt.Font;
import java.io.InputStream;

import java.util.Set;

import javax.sound.sampled.AudioInputStream;



/**
 *
 * @author Aziza
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    //private static String passText;
    private String passT;
    private Font f1;
    JLabel info1;
    JLabel info2;
    JLabel info3;

    
    public NewJFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        passT = "ВВЕДИТЕ ПАРОЛЬ";
        jPasswordField1.setEchoChar((char)0);
        jPasswordField1.setText("ВВЕДИТЕ ПАРОЛЬ");
        jPasswordField1.setForeground(Color.gray);
        f1 = new Font("Dialog", java.awt.Font.PLAIN, 34);
        info1 = new JLabel("ЗАПОЛНИТЕ ПУСТЫЕ ПОЛЯ");
        info2 = new JLabel("ВЫ УСПЕШНО ВОШЛИ");
        info3 = new JLabel("ПОЛЬЗОВАТЕЛЬ НЕ НАЙДЕН");
        info1.setFont(f1);
        info2.setFont(f1);
        info3.setFont(f1);
        //voice = new Voice("voxforge-ru-nsh");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DLMSPIV");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 162));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTextField2.setToolTipText("");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jPasswordField1.setToolTipText("");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPasswordField1)
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 38)); // NOI18N
        jLabel6.setText("ДОБРО ПОЖАЛОВАТЬ. ЧТОБЫ НАЧАТЬ ОБУЧЕНИЕ ВОЙДИТЕ ИЛИ ЗАРЕГИСТРИРУЙТЕСЬ В СИСТЕМЕ. ");
        jLabel6.setPreferredSize(new java.awt.Dimension(2358, 56));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setText("ПАРОЛЬ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel3.setText("ЛОГИН");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButton1.setText("ВХОД");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jButton2.setText("РЕГИСТРАЦИЯ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("БЕЛЫЙ ШРИФТ НА ЧЕРНОМ ФОНЕ");
        jRadioButton1.setToolTipText("");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ЖЕЛТЫЙ", "ОРНАЖЕВЫЙ", "ГОЛУБОЙ", "ЗЕЛЕНЫЙ" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("ЦВЕТ ФОНА:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("ШРИФТ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("ЦВЕТ:");

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jSlider1.setMaximum(60);
        jSlider1.setMinimum(38);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(48);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioButton2.setText("ЧЕРНЫЙ ШРИФТ НА БЕЛОМ ФОНЕ");
        jRadioButton2.setToolTipText("");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("ОЗВУЧИВАНИЕ");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(576, 576, 576)
                .addComponent(jLabel4)
                .addGap(364, 364, 364))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1862, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(75, 75, 75)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Logo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1879, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1879, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(750, 750, 750))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    PersonalAgent frame = new PersonalAgent();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField2.getText().length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, info1, "УВЕДОМЛЕНИЕ", JOptionPane.PLAIN_MESSAGE);
        } else if (jPasswordField1.getPassword().length == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, info1, "УВЕДОМЛЕНИЕ", JOptionPane.PLAIN_MESSAGE);
        } else {
            String user = jTextField2.getText();   // Collecting the input
            char[] pass = jPasswordField1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if (validate_login(user, pwd)) {
                JOptionPane.showMessageDialog(null, info2, "УВЕДОМЛЕНИЕ", JOptionPane.PLAIN_MESSAGE);
                LableQ.currentStudent = user;
                
                if(validate_levelKnow(LableQ.currentStudent, 0) && !validate_levelDis(LableQ.currentStudent, 0)){
                    new NewJFrame3().setVisible(true);
                    this.setVisible(false);
                } else if(validate_levelKnow(LableQ.currentStudent, 1)){
                    LableQ.levelEduStudent = "НАЧАЛЬНЫЙ";
                } else if(validate_levelKnow(LableQ.currentStudent, 2)){
                    LableQ.levelEduStudent = "СРЕДНИЙ";
                } else if(validate_levelKnow(LableQ.currentStudent, 3)){
                    LableQ.levelEduStudent = "ПРОДВИНУТЫЙ";
                }
                
                if(validate_levelDis(LableQ.currentStudent, 0)){
                                
				new NewJFrame4().setVisible(true);
                                this.setVisible(false);
                                System.out.println(LableQ.currentStudent);
                } else if(validate_levelDis(LableQ.currentStudent, 1) && !validate_levelKnow(LableQ.currentStudent, 0)){
                    LableQ.levelDisStudent = "МИОПИЯ";
                    new NewJFrame2().setVisible(true);
                    this.setVisible(false);
                } else if(validate_levelDis(LableQ.currentStudent, 2) && !validate_levelKnow(LableQ.currentStudent, 0)){
                    LableQ.levelDisStudent = "ГИПЕРМЕТРОПИЯ";
                    new NewJFrame2().setVisible(true);
                    this.setVisible(false);
                } else if(validate_levelDis(LableQ.currentStudent, 3) && !validate_levelKnow(LableQ.currentStudent, 0)){
                    LableQ.levelDisStudent = "АСТИГМАТИЗМ";
                    new NewJFrame2().setVisible(true);
                    this.setVisible(false);
                }
                
                
           
            } else {
                JOptionPane.showMessageDialog(null, info3, "УВЕДОМЛЕНИЕ", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean validate_login(String username,String password) {
   try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://sql12.freemysqlhosting.net/sql12170245?" + "user=sql12170245&password=fjym5utXqa");     
       PreparedStatement pst = conn.prepareStatement("Select * from sql12170245.users where login=? and password=?");
       pst.setString(1, username); 
       pst.setString(2, password);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next()){       
           return true;    
       }
           else 
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }       
}
    private boolean validate_levelDis(String student, int levelDis) {
          try{ 
        Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dlmspiv_bd?" + "user=root&password=root");     
       PreparedStatement pst = conn.prepareStatement("Select * from dlmspiv_bd.users where login=? and levelDis=?");
       pst.setString(1, student);
       pst.setInt(2, levelDis); 
       
        ResultSet rs = pst.executeQuery();  
       if(rs.next())            
           return true;    
       else
           return false; 
    }
           catch(Exception e){
       e.printStackTrace();
       return false;
        } 
    }
    
    private boolean validate_levelKnow(String student, int levelKnow) {
          try{ 
        Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dlmspiv_bd?" + "user=root&password=root");     
       PreparedStatement pst = conn.prepareStatement("Select * from dlmspiv_bd.users where login=? and levelKnow=?");
       pst.setString(1, student);
       pst.setInt(2, levelKnow); 
       
        ResultSet rs = pst.executeQuery();  
       if(rs.next())            
           return true;    
       else
           return false; 
    }
           catch(Exception e){
       e.printStackTrace();
       return false;
        } 
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        register = new NewJFrame1();
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
                        jTextField2.setForeground(Color.BLACK);
                if (jTextField2.getText().equals("ВВЕДИТЕ ЛОГИН")) {
                    jTextField2.setText("");
                }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if (jTextField2.getText().isEmpty()) {
                    jTextField2.setForeground(Color.GRAY);
                    jTextField2.setText("ВВЕДИТЕ ЛОГИН");
                }
    }//GEN-LAST:event_jTextField2FocusLost


    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
                jPasswordField1.setText("");
                jPasswordField1.setForeground(Color.BLACK);
                //String passText = new String(jPasswordField1.getPassword());
                if (jPasswordField1.getPassword().toString() == "ВВЕДИТЕ ПАРОЛЬ") {
                    jPasswordField1.setText("");
                }
                jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
                    
                    if (jPasswordField1.getPassword().length == 0) {
                    jPasswordField1.setForeground(Color.GRAY);
                    jPasswordField1.setEchoChar((char)0);
                    jPasswordField1.setText("ВВЕДИТЕ ПАРОЛЬ");
                }
             
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
   
            jPanel1.setBackground(Color.BLACK);
            jPanel2.setBackground(Color.BLACK);
            jPanel3.setBackground(Color.BLACK);
            

            jLabel2.setForeground(Color.WHITE);
            jLabel3.setForeground(Color.WHITE);
            jLabel4.setForeground(Color.WHITE);
            jLabel5.setForeground(Color.WHITE);
            jLabel6.setForeground(Color.WHITE);
            jLabel7.setForeground(Color.WHITE);
            jLabel8.setForeground(Color.WHITE);
            jLabel9.setForeground(Color.WHITE);
            jLabel10.setForeground(Color.WHITE);
            jButton1.setForeground(Color.WHITE);
            jButton2.setForeground(Color.WHITE);
            jButton3.setForeground(Color.WHITE);
            jRadioButton1.setForeground(Color.WHITE);
            jRadioButton2.setForeground(Color.WHITE);
            
            
            jButton1.setBackground(Color.BLACK);
            jButton2.setBackground(Color.BLACK);
            jButton3.setBackground(Color.BLACK);
            jRadioButton1.setBackground(Color.BLACK);
            jRadioButton2.setBackground(Color.BLACK);
            jSlider1.setBackground(Color.BLACK);

            

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        
        // TODO add your handling code here:
        //changeFont(jTextPane1, 20);
        jLabel3.setFont(new Font(jLabel3.getFont().getFontName(), jLabel3.getFont().getStyle(), jSlider1.getValue()));
        jLabel2.setFont(new Font(jLabel3.getFont().getFontName(), jLabel2.getFont().getStyle(), jSlider1.getValue()));

      
        jLabel4.setFont(new Font(jLabel3.getFont().getFontName(), jLabel4.getFont().getStyle(), jSlider1.getValue()));
        jLabel5.setFont(new Font(jLabel3.getFont().getFontName(), jLabel5.getFont().getStyle(), jSlider1.getValue()));
        jLabel6.setFont(new Font(jLabel3.getFont().getFontName(), jLabel6.getFont().getStyle(), jSlider1.getValue()));
        jLabel7.setFont(new Font(jLabel3.getFont().getFontName(), jLabel7.getFont().getStyle(), jSlider1.getValue()));

        
        
    }//GEN-LAST:event_jSlider1StateChanged
    InputStream sound =null;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:    
        
         

            
      
    

            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:

            jPanel1.setBackground(Color.WHITE);
            jPanel2.setBackground(Color.WHITE);
            jPanel3.setBackground(Color.WHITE);
            

            jLabel2.setForeground(Color.BLACK);
            jLabel3.setForeground(Color.BLACK);
            jLabel4.setForeground(Color.BLACK);
            jLabel5.setForeground(Color.BLACK);
            jLabel6.setForeground(Color.BLACK);
            jLabel7.setForeground(Color.BLACK);
            jLabel8.setForeground(Color.BLACK);
            jLabel9.setForeground(Color.BLACK);
            jLabel10.setForeground(Color.BLACK);
            jButton1.setForeground(Color.BLACK);
            jButton2.setForeground(Color.BLACK);
            jButton3.setForeground(Color.BLACK);
            jRadioButton1.setForeground(Color.BLACK);
            jRadioButton2.setForeground(Color.BLACK);
           
            
            jButton1.setBackground(Color.WHITE);
            jButton2.setBackground(Color.WHITE);
            jButton3.setBackground(Color.WHITE);
            jRadioButton1.setBackground(Color.WHITE);
            jRadioButton2.setBackground(Color.WHITE);
            jSlider1.setBackground(Color.WHITE);
            
       
           
            

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch (jComboBox1.getSelectedIndex()){
        case 0:
            jPanel1.setBackground(Color.WHITE);
            jPanel2.setBackground(Color.WHITE);
            jPanel3.setBackground(Color.WHITE);
            jButton1.setBackground(Color.WHITE);
            jButton2.setBackground(Color.WHITE);
            jButton3.setBackground(Color.WHITE);
            jRadioButton1.setBackground(Color.WHITE);
            jRadioButton2.setBackground(Color.WHITE);
            jSlider1.setBackground(Color.WHITE);
            break;    
        case 1: 
            jPanel1.setBackground(Color.YELLOW);
            jPanel2.setBackground(Color.YELLOW);
            jPanel3.setBackground(Color.YELLOW);
            jButton1.setBackground(Color.YELLOW);
            jButton2.setBackground(Color.YELLOW);
            jButton3.setBackground(Color.YELLOW);
            jRadioButton1.setBackground(Color.YELLOW);
            jRadioButton2.setBackground(Color.YELLOW);
            jSlider1.setBackground(Color.YELLOW);
            break;
        case 2:
            jPanel1.setBackground(Color.ORANGE);
            jPanel2.setBackground(Color.ORANGE);
            jPanel3.setBackground(Color.ORANGE);
            jButton1.setBackground(Color.ORANGE);
            jButton2.setBackground(Color.ORANGE);
            jButton3.setBackground(Color.ORANGE);
            jRadioButton1.setBackground(Color.ORANGE);
            jRadioButton2.setBackground(Color.ORANGE);
            jSlider1.setBackground(Color.ORANGE);
            break;
        case 3:
            jPanel1.setBackground(Color.BLUE);
            jPanel2.setBackground(Color.BLUE);
            jPanel3.setBackground(Color.BLUE);
            jButton1.setBackground(Color.BLUE);
            jButton2.setBackground(Color.BLUE);
            jButton3.setBackground(Color.BLUE);
            jRadioButton1.setBackground(Color.BLUE);
            jRadioButton2.setBackground(Color.BLUE);
            jSlider1.setBackground(Color.BLUE);
            break;
        case 4:
            jPanel1.setBackground(Color.GREEN);
            jPanel2.setBackground(Color.GREEN);
            jPanel3.setBackground(Color.GREEN);
            jButton1.setBackground(Color.GREEN);
            jButton2.setBackground(Color.GREEN);
            jButton3.setBackground(Color.GREEN);
            jRadioButton1.setBackground(Color.GREEN);
            jRadioButton2.setBackground(Color.GREEN);
            jSlider1.setBackground(Color.GREEN);
            break;
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            
            }
        });
    }
    
    private NewJFrame1 register;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
